---
title: "Glycocalyx Study Report"
author: "MSSP Consulting Group 4"
date: "12/15/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, highlight=FALSE)
knitr::opts_chunk$set(fig.width=6, fig.height=5,fig.align="center")

library(tidyverse)
library(readxl)
library(magrittr)
library(lmerTest)
library("rstanarm")
library("lme4")
library("bayesplot")
library("bruceR")
```

```{r}
#Read in height and coverage files
glyco_h <- read_excel("Glycocalyx_Feb(Heights_fix).xlsx", na = c("no good/none", "None/Not labeled"))
glyco_c <- read_excel("Glycocalyx_Feb(Coverage_fix).xlsx", na = c("no good/none", "no good /none", "None/Not labeled", "None/not labeled"))

#Filter out null rows
glyco_h <- filter(glyco_h, !is.na(Eye))
glyco_c <- filter(glyco_c, !is.na(Eye))

#Tidy the datasets
glyco_h <- glyco_h %>%
  pivot_longer(cols = -c(Eye, Region), names_to = "Outflow_Location", values_to = "height") %>%
  mutate(L_or_R = substr(Eye,5,5), monkey = substr(Eye,3,3)) %>%
  mutate(left = ifelse(L_or_R == "S",1,0)) %>%
  mutate(monkey = as.factor(monkey), Region = as.factor(Region), Outflow_Location = as.factor(Outflow_Location)) %>%
  select(Region, Outflow_Location, monkey, left, height) %>%
  filter(!is.na(height))

glyco_c <- glyco_c %>%
  pivot_longer(cols = -c(Eye, Region), names_to = "Outflow_Location", values_to = "coverage") %>%
  mutate(L_or_R = substr(Eye,5,5), monkey = substr(Eye,3,3)) %>%
  mutate(left = ifelse(L_or_R == "S",1,0)) %>%
  mutate(monkey = as.factor(monkey), Region = as.factor(Region), Outflow_Location = as.factor(Outflow_Location)) %>%
  select(Region, Outflow_Location, monkey, left, coverage) %>%
  filter(!is.na(coverage))

glyco_c <- mutate(glyco_c, coverage_p = coverage/100)

# check <- glyco_c %>% count(Outflow_Location)
# check
# check2 <- glyco_c %>% count(Region)
# check2
```


```{r}
#Normal distribution groups checks
hist(qlogis(filter(glyco_c, Region == "Control")$coverage_p))
hist(qlogis(filter(glyco_c, Region == "Control High Flow")$coverage_p))  #1.10
hist(qlogis(filter(glyco_c, Region == "Control Low Flow")$coverage_p)) #1.10
hist(qlogis(filter(glyco_c, Region == "Non-Lasered")$coverage_p)) #0.82
hist(log(filter(glyco_h, Region == "Control")$height)) #0.27
hist(log(filter(glyco_h, Region == "Control High Flow")$height))  #0.15
hist(log(filter(glyco_h, Region == "Control Low Flow")$height)) #0.15
hist(log(filter(glyco_h, Region == "Non-Lasered")$height)) #0.138
hist(qlogis(filter(glyco_c, Outflow_Location == "SC")$coverage_p)) #0.83
hist(qlogis(filter(glyco_c, Outflow_Location == "CC")$coverage_p))
#1.13
hist(qlogis(filter(glyco_c, Outflow_Location == "ISV")$coverage_p))
#1.03
hist(qlogis(filter(glyco_c, Outflow_Location == "ESV")$coverage_p))
#0.92
hist(qlogis(filter(glyco_c, Outflow_Location == "TM")$coverage_p))
#0.53
hist(qlogis(filter(glyco_c, Outflow_Location == "Uveal")$coverage_p))
#1.05
hist(qlogis(filter(glyco_c, Outflow_Location == "Corneaoscleral")$coverage_p))
#1.42
hist(log(filter(glyco_h, Outflow_Location == "SC")$height)) #0.11
hist(log(filter(glyco_h, Outflow_Location == "CC")$height)) #0.13
hist(log(filter(glyco_h, Outflow_Location == "ISV")$height)) #0.19
hist(log(filter(glyco_h, Outflow_Location == "ESV")$height)) #0.15
hist(log(filter(glyco_h, Outflow_Location == "TM")$height)) #0.10
hist(log(filter(glyco_h, Outflow_Location == "Uveal")$height)) #0.09
hist(log(filter(glyco_h, Outflow_Location == "Corneaoscleral")$height)) #0.09

#Variance group checks
var(filter(glyco_c, Region == "Control")$coverage_p) #0.87
var(filter(glyco_c, Region == "Control High Flow")$coverage_p)  #1.10
var(filter(glyco_c, Region == "Control Low Flow")$coverage_p) #1.10
var(filter(glyco_c, Region == "Non-Lasered")$coverage_p) #0.82

var(log(filter(glyco_h, Region == "Control")$height)) #0.27
var(log(filter(glyco_h, Region == "Control High Flow")$height))  #0.15
var(log(filter(glyco_h, Region == "Control Low Flow")$height)) #0.15
var(log(filter(glyco_h, Region == "Non-Lasered")$height)) #0.138



var(filter(glyco_c, Outflow_Location == "SC")$coverage_p) #0.83
var(filter(glyco_c, Outflow_Location == "CC")$coverage_p)
#1.13
var(filter(glyco_c, Outflow_Location == "ISV")$coverage_p)
#1.03
var(filter(glyco_c, Outflow_Location == "ESV")$coverage_p)
#0.92
var(filter(glyco_c, Outflow_Location == "TM")$coverage_p)
#0.53
var(filter(glyco_c, Outflow_Location == "Uveal")$coverage_p)
#1.05
var(filter(glyco_c, Outflow_Location == "Corneaoscleral")$coverage_p)
#1.42

var(log(filter(glyco_h, Outflow_Location == "SC")$height)) #0.11
var(log(filter(glyco_h, Outflow_Location == "CC")$height)) #0.13
var(log(filter(glyco_h, Outflow_Location == "ISV")$height)) #0.19
var(log(filter(glyco_h, Outflow_Location == "ESV")$height)) #0.15
var(log(filter(glyco_h, Outflow_Location == "TM")$height)) #0.10
var(log(filter(glyco_h, Outflow_Location == "Uveal")$height)) #0.09
var(log(filter(glyco_h, Outflow_Location == "Corneaoscleral")$height)) #0.09
```





```{r,include=FALSE}
#Model to show results by plotting
hist(glyco_c$coverage_p)
sfit_c2 <- stan_lmer(qlogis(coverage_p) ~ 1 + Region + Outflow_Location +  (1|Region:Outflow_Location) + left + (1|monkey), data = glyco_c)

sfit_h2 <- stan_lmer(log(height) ~ 1 +Region+Outflow_Location+  (1|Region:Outflow_Location) + left + (1|monkey), data = glyco_h)

#postsample=as.matrix(sfit_c2)
#postsample=as.matrix(sfit_h2)
```

```{r}
tuk_plot <- function (x, main, ...){
    for (i in seq_along(x)) {
        xi <- x[[i]][, -4L, drop = FALSE]
        yvals <- nrow(xi):1L
        dev.hold()
        on.exit(dev.flush())
        plot(c(xi[, "lwr"], xi[, "upr"]), rep.int(yvals, 
            2L), type = "n", axes = FALSE, xlab = "", 
            ylab = "", main = NULL, ...)
        axis(1, ...)
        axis(2, at = nrow(xi):1, labels = dimnames(xi)[[1L]], 
            srt = 0, ...)
        abline(h = yvals, lty = 1, lwd = 0.5, col = "lightgray")
        abline(v = 0, lty = 2, lwd = 0.5, ...)
        segments(xi[, "lwr"], yvals, xi[, "upr"], 
            yvals, ...)
        segments(as.vector(xi), rep.int(yvals - 0.1, 3L), as.vector(xi), 
            rep.int(yvals + 0.1, 3L), ...)
        title(main = paste0(format(100 * attr(x, "conf.level"), 
            digits = 2L), "% confidence level ", main ,"\n"), 
            xlab = paste("Differences in mean levels of", 
                names(x)[i]))
        box()
        dev.flush()
        on.exit()
    }
}
```


Tukey Tests
```{r, fig.height=10}
regions <- c("Control", "Control High Flow", "Control Low Flow", "Non-Lasered")
ofs <- c("CC", "ESV", "ISV", "SC", "TM", "Corneaoscleral", "Uveal")

for (region in regions){
  c_r <- filter(glyco_c, Region == region)
  cov_reg <- aov(qlogis(coverage_p) ~ Outflow_Location + left + monkey, data = c_r)
  r1 <- TukeyHSD(cov_reg, which = "Outflow_Location", conf.level = 0.95)
  op=par(mar=c(4.2,14,3.8,5))
  tuk_plot(r1, paste(region, "-" ,"Coverage"), las = 1)
  par(op)
}


for (region in regions){
  h_r <- filter(glyco_h, Region == region)
  h_reg <- aov(log(height) ~ Outflow_Location + left + monkey, data = h_r)
  r1 <- TukeyHSD(h_reg, which = "Outflow_Location", conf.level = 0.95)
  op=par(mar=c(4.2,14,3.8,5))
  tuk_plot(r1, paste(region, "-" ,"Height"), las = 1)
  par(op)
}


```

```{r}

for (of in ofs){
  c_o <- filter(glyco_c, Outflow_Location == of)
  cov_reg <- aov(qlogis(coverage_p) ~ Region + left + monkey, data = c_o)
  r3 <- TukeyHSD(cov_reg, which = "Region", conf.level = 0.95)
  op=par(mar=c(4.2,14,3.8,2))
  tuk_plot(r3, paste(of, "-" ,"Coverage"), las = 1)
  par(op)
}

for (of in ofs){
  h_o <- filter(glyco_h, Outflow_Location == of)
  h_reg <- aov(log(height) ~ Region + left + monkey, data = h_o)
  r3 <- TukeyHSD(h_reg, which = "Region", conf.level = 0.95)
  op=par(mar=c(4.2,14,3.8,2))
  tuk_plot(r3, paste(of, "-" ,"Height"), las = 1)
  par(op)
}


# 
# hei_reg <- aov(log(height) ~ Region + Outflow_Location + left + monkey, data = glyco_h)
# r2 <- TukeyHSD(hei_reg, which = c("Region", "Outflow_Location"), conf.level = 0.95)




# op=par(mar=c(4.2,14,3.8,2))
# plot(r2, las = 1)
# par(op)


```

```{r}
sc <- summary(sfit_c2, 
       probs = c(0.025, 0.975),
        digits = 2)
sh <- summary(sfit_h2, 
       probs = c(0.025, 0.975),
        digits = 2)
```


```{r}
posterior_interval(sfit_c2, prob=0.95)
posterior_interval(sfit_h2, prob=0.95)
### https://stephens999.github.io/fiveMinuteStats/summarize_interpret_posterior.html

yrep <- posterior_predict(sfit_h2)

g <- arrange(glyco_h, Region)
ppc_ribbon_grouped(y = log(g$height), yrep = yrep, y_draw = "points", group = g$Outflow_Location)
```

```{r}
pp_check(sfit_c2)
pp_check(sfit_h2)
```

```{r}
a<-fixef(sfit_c2) #fixed effect c
postsample1<-as.matrix(a)
postsample1<-as.table(postsample1)
postsample1

b<-fixef(sfit_h2) #fixed effect h
postsample2<-as.matrix(b)
postsample2

# ranef(sfit_c2) #random effect c
# ranef(sfit_h2) #random effect h

# plot(sfit_c2) # fixed and random effect plot
# plot(sfit_h2) # fixed and random effect plot
```

```{r}
plot(sfit_c2, pars=c("RegionControl High Flow","RegionControl Low Flow","RegionNon-Lasered","Outflow_LocationCorneaoscleral","Outflow_LocationESV","Outflow_LocationISV","Outflow_LocationSC","Outflow_LocationTM","Outflow_LocationUveal"))

plot(sfit_c2, regex_pars = "^b\\[\\(Intercept)\\ Region")

plot(sfit_h2, pars=c("RegionControl High Flow","RegionControl Low Flow","RegionNon-Lasered","Outflow_LocationCorneaoscleral","Outflow_LocationESV","Outflow_LocationISV","Outflow_LocationSC","Outflow_LocationTM","Outflow_LocationUveal"))

plot(sfit_h2, regex_pars = "^b\\[\\(Intercept)\\ Region")

coefs_c <- coef(sfit_c2)$`Region:Outflow_Location`
se_c <- se(sfit_c2)[12:37]
```

```{r}
# significant
#https://www.zhihu.com/question/273644403

hist(qlogis(glyco_c$coverage_p))
hist(log(glyco_h$height))


x <- qlogis(glyco_c$coverage_p)
h<-hist(x, breaks=10, col="red",
   main="Histogram with Normal Curve")
xfit<-seq(min(x),max(x),length=40)
yfit<-dnorm(xfit,mean=mean(x),sd=sd(x))
yfit <- yfit*diff(h$mids[1:2])*length(x)
lines(xfit, yfit, col="blue", lwd=2)

x <- log(glyco_h$height)
h<-hist(x, breaks=15, col="red",
   main="Histogram with Normal Curve")
xfit<-seq(min(x),max(x),length=40)
yfit<-dnorm(xfit,mean=mean(x),sd=sd(x))
yfit <- yfit*diff(h$mids[1:2])*length(x)
lines(xfit, yfit, col="blue", lwd=2)
```


```{r}
boxplot(qlogis(coverage_p)~Outflow_Location,data=glyco_c,
   xlab="location", ylab="coverage")
boxplot(qlogis(coverage_p)~Region,data=glyco_c,
   xlab="location", ylab="coverage")

boxplot(log(height)~Outflow_Location,data=glyco_h,
   xlab="location", ylab="height")
boxplot(log(height)~Region,data=glyco_h,
   xlab="location", ylab="height")

ggplot(glyco_c, aes(x=Outflow_Location, y=coverage, color=Region)) +
  geom_boxplot() +
  ggtitle("Coverage isolating by Outflow Location")

ggplot(glyco_c, aes(x=Region, y=coverage, color=Outflow_Location)) +
  geom_boxplot() +
  ggtitle("Coverage isolating by Region")

ggplot(glyco_h, aes(x=Outflow_Location, y=height, color=Region)) +
  geom_boxplot() +
  ggtitle("Height isolating by Outflow Location")

ggplot(glyco_h, aes(x=Region, y=height, color=Outflow_Location)) +
  geom_boxplot() +
  ggtitle("Height isolating by Region")
```



```{r}
mean(glyco_h$height)
mean(filter(glyco_h, Region == "Control")$height)
mean(filter(glyco_h, Region == "Control High Flow")$height)
mean(filter(glyco_h, Region == "Control Low Flow")$height)
mean(filter(glyco_h, Region == "Non-Lasered")$height)
print("---")
mean(filter(glyco_h, Outflow_Location == "CC")$height)
mean(filter(glyco_h, Outflow_Location == "ESV")$height)
mean(filter(glyco_h, Outflow_Location == "ISV")$height)
mean(filter(glyco_h, Outflow_Location == "SC")$height)
mean(filter(glyco_h, Outflow_Location == "TM")$height)
mean(filter(glyco_h, Outflow_Location == "Corneaoscleral")$height)
mean(filter(glyco_h, Outflow_Location == "Uveal")$height)

```




